spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    url: ${DB_URL:localhost:5432}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        types:
          print:
            banner: false
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: ${DB_SCHEMA:public}
    show-sql: true